version: '3.8'

services:
  gisweb:
    build:
      context: ./webapp
      dockerfile: Dockerfile
    command: bash -c "/usr/local/bin/gunicorn geofeatures.wsgi:application --bind 0.0.0.0:8000 --access-logfile - --workers 4 --timeout 300"
    volumes:
      - ./webapp:/code
    ports:
      - "8000:8000"
    expose:
      - 8000
    depends_on:
      - gisdb
    env_file:
      - .env
    restart: always
  
  gisdb:
    image: postgis/postgis:14-3.3
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - gisdb_data:/var/lib/postgresql/data
    restart: always

volumes:
  gisdb_data:
